# Azure Databricks Build Pipeline
# azure-pipelines.yml
#hello

trigger:
- release

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.8'
  inputs:
    versionSpec: 3.8

- script: |
    pip install pytest requests setuptools wheel
    pip install -U databricks-connect==13.0.*
  displayName: 'Load Python Dependencies'

- script: |
    echo "y
    $(DATABRICKS_ADDRESS)
    $(DATABRICKS_API_TOKEN)
    $(DATABRICKS_CLUSTER_ID)
    $(DATABRICKS_ORG_ID)
    $(DATABRICKS_PORT)" | databricks-connect configure
  displayName: 'Configure DBConnect'

- checkout: self
  persistCredentials: true
  clean: true

<<<<<<< HEAD
=======
- script: git checkout main
  displayName: 'Get Latest Branch'

>>>>>>> 433c043ec606d75643da65ce1a42af3109ba979f

- script: |
    cd $(Build.Repository.LocalPath)/package
    python3 setup.py sdist bdist_wheel
    ls dist/
    echo $(Build.Repository.LocalPath)
    echo $(Build.BinariesDirectory)
  displayName: 'Build Python Wheel for Libs'

- script: |
    git diff --name-only --diff-filter=AMR HEAD^1 HEAD | xargs -I '{}' cp --parents -r '{}' $(Build.BinariesDirectory)

    mkdir -p $(Build.BinariesDirectory)/package/libs
    cp $(Build.Repository.LocalPath)/package/dist/*.* $(Build.BinariesDirectory)/package/libs

    mkdir -p $(Build.BinariesDirectory)/notebooks
    cp -r $(Build.Repository.LocalPath)/notebooks/* $(Build.BinariesDirectory)/notebooks

    mkdir -p $(Build.BinariesDirectory)/cicd-scripts
    cp $(Build.Repository.LocalPath)/cicd-scripts/*.* $(Build.BinariesDirectory)/cicd-scripts

  displayName: 'Get Changes'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'DatabricksBuild'